# Generated by Django 4.2.6 on 2024-06-09 12:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Survivor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('last_location_latitude', models.FloatField()),
                ('last_location_longitude', models.FloatField()),
                ('infected', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Resource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resource_type', models.CharField(choices=[('water', 'Water'), ('food', 'Food'), ('medication', 'Medication'), ('ammunition', 'Ammunition')], max_length=20)),
                ('quantity', models.PositiveIntegerField()),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resources', to='api.survivor')),
            ],
        ),
    ]
